Asciidoc Linting
Make blocking asciidoc syntax errors automatic.

Change-Id: Ica1a234825d2edf87feda4757abed7a0ed4de16f
Reviewed-on: http://review.couchbase.org/c/couchbase-operator/+/143187
Tested-by: Build Bot <build@couchbase.com>
Reviewed-by: Simon Murray <simon.murray@couchbase.com>

diff --git a/scripts/asciidoc-lint b/scripts/asciidoc-lint
--- a/scripts/asciidoc-lint
+++ b/scripts/asciidoc-lint
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-set -eu -o pipefail
+set -e -o pipefail
 shopt -s inherit_errexit
 
 # FILTER allows us to pre-process the source and discard irrelevant parts.
@@ -54,5 +54,14 @@ done
 if [[ ${FAIL} != "" ]]; then
   echo "Documentation contains errors"
   echo "    run 'aspell check ${CHECK_ARGS}' to fix typos or add to .aspell.en.pws"
+  exit 1
+fi
+
+# Now that your general spelling has been corrected, let's look at syntax...
+npm install
+WARNINGS=$(node_modules/@antora/cli/bin/antora generate scripts/playbook.yaml 2>&1 | sed -e /^.*tabs.*$/d)
+if [[ "${WARNINGS}" != "" ]]; then
+  echo "Asciidoc markup contains errors"
+  echo "${WARNINGS}" | sed 's/^/    /g'
   exit 1
 fi
